### ISSUE TITLE
Bill of Materials

### ISSUE THREAD

**Issue by Rukongai** [psy0rz/meowton#1]
Not really an issue, but it'd be helpful for folks looking to replicate this for a consolidated Bill of Materials!

Excellent work here. Excited to get working on it.

**Comment by charlottecharles** [comment]
This is an amazing project that I would love to work on. A full bill of materials would be helpful to know how much of it I should try to tackle.

**Comment by psy0rz** [comment]
Every module on the wiki starts with a Requirements section.

You're probably too lazy to open those pages and read them, but i'm much lazier that. :)

So i don't feel like creating that bill of materials and maintaining basicalaly two lists of requirements. :P 

(Pull requests are welcome offcourse)

**Comment by Rukongai** [comment]
I mean, I have built the feeder at this point, as well as designing a custom PCB for the project (which i'm glad to open a PR for as well)

I will gladly put together a BOM, and I appreciate the work you've done in creating this project - I was just highlighting a pain point in beginning this, which was having to move between a bunch of different pages making sure I didn't miss anything in my first order. A singular BOM would make things much easier.

**Comment by psy0rz** [comment]
Oh that is great to hear! :)

I was planning to some day make a PCB for it, but its not my greatest hobby. Would love to see  a PR for it indeed.

Will it be a single pc with all the electronics on it? Or will it have mounts for the pre-fab modules i'm using?

Edwin

**Comment by Rukongai** [comment]
I refactored the design a little bit, and have a new shipment of boards coming on Thursday

I will test out the new design and then if it works i'll do a PR. 

This is the first time i've designed a pcb, so it's not the prettiest. I'm working on a 3rd version that's a little more complicated, that removes the need for buying a dev board or separate hx711 modules, integrating the core circuits onto a single board (and removing things like the usb ttyl circuit from the dev board) for a smaller footprint.

though that'll require a separate device for flashing the esp32.

The board itself is just a pcb that connects the dev board to the 5 hx711s with solder smd pads for all the load sensors and servo. It mounts to any flat surface with 3 m3 screws. I'd like to get it to where it can mount inside the dispenser base. I'm getting comfortable enough with fusion to try and remixing the base to that end.

It's all in all been a fun project and i've learned a ton. Thanks for putting it together.
