### ISSUE TITLE
Thank you!

### ISSUE THREAD

**Issue by necipharmanci** [psy0rz/meowton#3]
Hello, Do you think it is okay if I use Nodemcu Esp32 wifi instead of Raspberry Pi? Your project impressed me very much, I want to do this for my cats, but I need your help in answering this question.

**Comment by psy0rz** [comment]
The old version , here was for esp32: https://github.com/psy0rz/meowton/tree/master

I cant give you any support for the old version, so you would be on your own when you have issue.

However we just switched to RPI, so i would recommend that. (It function much better and has build in graphs and stuff)

Edwin
